"""L1 statistics: re-check the known data defects on every game.

Reads ``<root>/<build>/build_results.json`` and ``games.parquet``; writes
``reports/l1_stats.json`` (one record per archive / game) and ``reports/l1_summary.md``
(distributions across games, per-defect checks, games needing attention). Numbers only, no
coordinates, so both files are committed.

Usage:
    uv run python scripts/l1_report.py --build scratch/l1_full
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import polars as pl

from nbacore import paths

REPO = Path(__file__).resolve().parents[1]
# HoopTransformer README: games said to lack the shot clock (list carried over from ghost-defense)
HOOP_NO_SHOTCLOCK = [
    "0021500040", "0021500046", "0021500050", "0021500052", "0021500065", "0021500109",
    "0021500129", "0021500237", "0021500543", "0021500599", "0021500646", "0021500652",
]  # fmt: skip
RAW_KEYS = [
    "n_events", "n_events_no_moments", "n_duplicate_conflicts", "n_frames_no_ball",
    "n_frames_shotclock_null", "frac_shotclock_null_when_gc_le_24", "unix_dt_ms_mode",
    "n_events_unix_nonmonotonic", "n_events_gc_increase", "max_gc_increase_in_event",
    "player_z_nonzero", "n_roster_variants", "frac_frames_any_oob", "entities_per_frame",
    "periods", "ball_z_max", "warnings",
]  # fmt: skip


def per_game_records(results: list[dict], games: pl.DataFrame) -> list[dict]:
    g = {r["archive_name"]: r for r in games.iter_rows(named=True) if r["archive_name"]}
    out = []
    for r in results:
        row = g.get(r["archive_name"], {})
        rec = {
            "archive_name": r["archive_name"],
            "status": r["status"],
            "game_id": row.get("game_id"),
            "game_id_source": row.get("game_id_source"),
            "game_date": row.get("game_date"),
            "split": row.get("split"),
            "fold": row.get("fold"),
            "seconds": r.get("seconds"),
        }
        if r["status"] == "ok":
            rec["dedup"] = r["dedup"]
            rec["direction"] = {k: v for k, v in r["direction"].items() if k != "game_id"}
            rec["raw"] = {k: r["raw_stats"][k] for k in RAW_KEYS}
        elif "error" in r:
            rec["error"] = r["error"]
        out.append(rec)
    return out


def dist(x) -> str:
    a = np.asarray([v for v in x if v is not None], dtype=float)
    if a.size == 0:
        return "n/a"
    q = np.quantile(a, [0, 0.05, 0.5, 0.95, 1])
    return " / ".join(f"{v:.4g}" for v in q)


def summary_md(recs: list[dict], games: pl.DataFrame) -> str:
    ok = [r for r in recs if r["status"] == "ok"]
    D = pl.DataFrame(
        [
            {
                "game_id": r["game_id"],
                **{f"d_{k}": v for k, v in r["dedup"].items()},
                **{
                    f"r_{k}": r["raw"][k]
                    for k in RAW_KEYS
                    if not isinstance(r["raw"][k], dict | list)
                },
                "consistency": r["direction"]["overall_consistency"],
                "min_period_consistency": r["direction"]["min_period_consistency"],
                "overruled": r["direction"]["n_period_votes_overruled"],
                "teams_agree": r["direction"]["teams_agree"],
                "n_ent_ne_11": sum(
                    v for k, v in r["raw"]["entities_per_frame"].items() if k != "11"
                ),
                "n_ent_lt_10": sum(
                    v for k, v in r["raw"]["entities_per_frame"].items() if int(k) < 10
                ),
                "n_ent_gt_11": sum(
                    v for k, v in r["raw"]["entities_per_frame"].items() if int(k) > 11
                ),
                "n_ot": sum(1 for p in r["raw"]["periods"] if int(p) > 4),
            }
            for r in ok
        ]
    ).sort("game_id")
    fu = D["d_unique_frames"].cast(pl.Float64)
    L: list[str] = []
    w = L.append
    w("# L1 statistics (all games)\n")
    w("Generated by `scripts/l1_report.py` from the full L1 build. Distributions are across games:")
    w("**min / 5 % / median / 95 % / max**.\n")
    w("## Games\n")
    w("| status | games |\n|---|---|")
    for s, n in games.group_by("status").len().sort("status").iter_rows():
        w(f"| {s} | {n} |")
    w("")
    odd = games.filter(pl.col("status") != "ok")
    w(
        "| game_id | status | id source | date | archive | visitor @ home |\n|---|---|---|---|---|---|"
    )
    for r in odd.iter_rows(named=True):
        w(
            f"| {r['game_id']} | {r['status']} | {r['game_id_source']} | {r['game_date']} | "
            f"{r['archive_name']} | {r['visitor_abbr']} @ {r['home_abbr']} |"
        )
    w("")
    w("## Known data defects, re-checked\n")
    w("| # | quantity (per game) | distribution | expected |\n|---|---|---|---|")
    rows = [
        ("1", "moment duplicate fraction", dist(D["d_moment_dup_fraction"]), "54–67 %"),
        ("2", "split-frame conflicts (same key, different content)", dist(D["r_n_duplicate_conflicts"]), "rare; 74 in 0021500230"),
        ("2", "games with any split-frame conflict", str((D["r_n_duplicate_conflicts"] > 0).sum()), ""),
        ("3", "events with an upward game-clock correction", dist(D["r_n_events_gc_increase"] / D["r_n_events"]), "≈ 25 % of events"),
        ("3", "largest upward correction in an event (s)", dist(D["r_max_gc_increase_in_event"]), "max +24.65 s (0021500292)"),
        ("3", "clock jumps > 1 s in the deduped timeline", dist(D["d_n_clock_jumps"]), ""),
        ("4", "gaps > 60 ms", dist(D["d_n_gaps"]), "≈ 100 per game"),
        ("4", "continuity segments", dist(D["d_n_segments"]), ""),
        ("5", "frames with null shot clock (fraction)", dist(D["d_shot_clock_null_frames"] / fu), "common when stopped / last 24 s"),
        ("5", "null shot clock fraction when game clock ≤ 24 s", dist(D["r_frac_shotclock_null_when_gc_le_24"]), ""),
        ("6", "frames without the ball (fraction)", dist(D["d_frames_no_ball"] / fu), "≈ 0.5 %"),
        ("6", "frames with ≠ 11 entities (fraction)", dist(D["n_ent_ne_11"] / fu), ""),
        ("6", "frames with < 10 entities", dist(D["n_ent_lt_10"]), "very rare"),
        ("6", "frames with > 11 entities", dist(D["n_ent_gt_11"]), "none (no referees)"),
        ("11", "frames with any entity out of bounds (fraction)", dist(D["r_frac_frames_any_oob"]), "9–10 %"),
        ("–", "tracking events without moments (fraction)", dist(D["r_n_events_no_moments"] / D["r_n_events"]), "0–14 %"),
        ("–", "Δunix mode (ms)", dist(D["r_unix_dt_ms_mode"]), "40 (25 Hz)"),
        ("–", "events with non-monotone unix_ms", dist(D["r_n_events_unix_nonmonotonic"]), "0"),
        ("–", "player z ≠ 0 rows", dist(D["r_player_z_nonzero"]), "0"),
        ("–", "roster variants per game", dist(D["r_n_roster_variants"]), "1"),
        ("–", "unique frames", dist(D["d_unique_frames"]), "≈ 80 k"),
    ]  # fmt: skip
    for r in rows:
        w("| " + " | ".join(r) + " |")
    w(f"\nOvertime games: {(D['n_ot'] > 0).sum()}.\n")
    w("## Attack direction\n")
    w(f"- overall consistency: {dist(D['consistency'])}; mean {D['consistency'].mean():.4f}")
    w(f"- lowest per-period consistency: {dist(D['min_period_consistency'])}")
    w(f"- games where the two teams' votes disagree: {(~D['teams_agree']).sum()}")
    w(
        f"- games with period votes overruled by the structure constraint: {(D['overruled'] > 0).sum()}"
    )
    low = D.filter(pl.col("consistency") < 0.9)
    w(f"- games below 0.9 (acceptance requires a manual check): {low.height}")
    for r in low.iter_rows(named=True):
        w(f"  - {r['game_id']}: {r['consistency']:.3f}")
    w("")
    w("## Shot clock: games listed by HoopTransformer as missing it\n")
    med = (D["d_shot_clock_null_frames"] / fu).median()
    w(f"League median null fraction: {med:.4f}.\n")
    w(
        "| game_id | status | null shot-clock frames | fraction | null when gc ≤ 24 s |\n|---|---|---|---|---|"
    )
    st = dict(games.select(["game_id", "status"]).iter_rows())
    for gid in HOOP_NO_SHOTCLOCK:
        r = D.filter(pl.col("game_id") == gid)
        if r.height == 0:
            w(f"| {gid} | {st.get(gid, 'not in tracking')} | – | – | – |")
            continue
        r = r.row(0, named=True)
        w(
            f"| {gid} | ok | {r['d_shot_clock_null_frames']} | "
            f"{r['d_shot_clock_null_frames'] / r['d_unique_frames']:.4f} | "
            f"{r['r_frac_shotclock_null_when_gc_le_24']:.3f} |"
        )
    top = (
        D.with_columns((pl.col("d_shot_clock_null_frames") / fu).alias("f"))
        .sort("f", descending=True)
        .head(15)
    )
    w("\nTop 15 games by null shot-clock fraction (★ = HoopTransformer list):\n")
    w("| game_id | fraction |\n|---|---|")
    for r in top.iter_rows(named=True):
        star = " ★" if r["game_id"] in HOOP_NO_SHOTCLOCK else ""
        w(f"| {r['game_id']}{star} | {r['f']:.4f} |")
    w("")
    return "\n".join(L)


def splits_md(games: pl.DataFrame) -> str:
    ok = games.filter(pl.col("status") == "ok")
    L = [
        "# Fixed game split (L4, data v1.0)",
        "",
        "Generated by `scripts/l1_report.py`; rule in `nbacore.splits`, fixed once for all games.",
        "",
        "## Rules",
        "",
        "- Scope: every game with `status == ok` in `games.parquet`, independent of what a",
        "  project has downloaded. Other games have null `split` / `fold` / `parity`.",
        "- `split`: games sorted by (`game_date`, `game_id`); the first 80 % (rounded) form the",
        "  training pool, the rest is `test`. `val` = 10 % (rounded) of the training pool drawn",
        "  at random with `numpy.random.default_rng(9)`; the remainder is `train`.",
        "- `fold` (0-4): games sorted by `game_id`, permuted with `default_rng(9)`, fold =",
        "  position in the permutation mod 5. Independent of `split` (for cross-fitting).",
        "- `parity` (0/1): position in (`game_date`, `game_id`) order mod 2 (odd/even games).",
        "",
        "## Sets",
        "",
        "| split | games | first date | last date |",
        "|---|---|---|---|",
    ]
    for r in (
        ok.group_by("split")
        .agg(pl.len(), pl.col("game_date").min().alias("lo"), pl.col("game_date").max().alias("hi"))
        .sort("lo")
        .iter_rows(named=True)
    ):
        L.append(f"| {r['split']} | {r['len']} | {r['lo']} | {r['hi']} |")
    L += ["", "| fold | games |", "|---|---|"]
    for f, n in ok.group_by("fold").len().sort("fold").iter_rows():
        L.append(f"| {f} | {n} |")
    L += ["", "| parity | games |", "|---|---|"]
    for f, n in ok.group_by("parity").len().sort("parity").iter_rows():
        L.append(f"| {f} | {n} |")
    cut = ok.filter(pl.col("split") == "test").sort(["game_date", "game_id"]).row(0, named=True)
    same_day = ok.filter(pl.col("game_date") == cut["game_date"]).sort("game_id")
    L += [
        "",
        f"The train/test boundary falls on {cut['game_date']}: games of that day with id <",
        f"{cut['game_id']} are in the training pool ("
        + ", ".join(f"{r['game_id']} {r['split']}" for r in same_day.iter_rows(named=True))
        + ").",
        "",
    ]
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--build", required=True, help="build dir relative to the data root")
    args = ap.parse_args()
    build = paths.data_root() / args.build
    results = json.loads((build / "build_results.json").read_text(encoding="utf-8"))
    games = pl.read_parquet(build / "games.parquet")
    recs = per_game_records(results, games)
    out = REPO / "reports"
    out.mkdir(exist_ok=True)
    (out / "l1_stats.json").write_text(json.dumps(recs, indent=1), encoding="utf-8")
    (out / "l1_summary.md").write_text(summary_md(recs, games), encoding="utf-8")
    (REPO / "docs" / "splits.md").write_text(splits_md(games), encoding="utf-8")
    print(f"wrote {out / 'l1_stats.json'} ({len(recs)} records), l1_summary.md, docs/splits.md")


if __name__ == "__main__":
    main()
